version: 2

build:
   os: ubuntu-24.04
   tools:
       python: "latest"
   jobs:
      create_environment:
         - asdf plugin add pixi
         - asdf install pixi latest
         - asdf global pixi latest
      install:
         - pixi install -e doc
      build:
         html:
           # TODO: override this with the `build` task defined in pyproject.toml?
            - pixi run -e doc sphinx-build -T -b html docs $READTHEDOCS_OUTPUT/html
