name: multiurbanpy
channels:
  - conda-forge
dependencies:
  - gdal=3.10.2
  - myst-parser=4.0.1
  - nbsphinx=0.9.7
  - pip=25.0.1
  - pydata-sphinx-theme=0.16.1
  - python=3.13
  - setuptools=75.8.2
  - sphinx=8.2.3
