name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - "*"

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
        environment: [test]
        include:
          - os: macos-latest
            python-version: "3.13"
          - os: windows-latest
            python-version: "3.13"

    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v4

      - uses: prefix-dev/setup-pixi@v0.9.2
        with:
          pixi-version: v0.58.0
          environments: ${{ matrix.environment }}
          frozen: true

      - name: run tests
        run: pixi run -e ${{ matrix.environment }} test

      - name: upload coverage reports to Codecov
        uses: codecov/codecov-action@v5.5.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: list files
        run: ls -l .
